### ISSUE TITLE
can you share your code

### ISSUE THREAD

**Issue by MOMOANNIE** [superbunny38/Multi-Object-Semantic-Segmentation#1]
Hi can you share your code? I want to learn how the boundary loss is added

**Comment by superbunny38** [comment]
Hello, thank you for sharing your need :)
If you tell me your gmail, I'll give you the access via e-mail.

**Comment by MOMOANNIE** [comment]
> Hello, thank you for sharing your need :) If you tell me your gmail, I'll give you the access via e-mail.

Thank you for your reply, my email is gdutchu@outlook.com

**Comment by superbunny38** [comment]
> > Hello, thank you for sharing your need :) If you tell me your gmail, I'll give you the access via e-mail.
> 
> Thank you for your reply, my email is [gdutchu@outlook.com](mailto:gdutchu@outlook.com)

I shared it now :)
